### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by Oedipsos**
For local files generated by Jupyter notebooks and Python kernels

### CODE REVIEW

**Comment by bknaepen** [comment]
@YelyzavetaV 

Maybe we could add? Anything else?

.vscode
.DS_Store
settings.json
*.pyc

**Comment by YelyzavetaV** [comment]
> @YelyzavetaV
> 
> Maybe we could add? Anything else?
> 
> .vscode
> .DS_Store
> settings.json
> *.pyc

All that you mentioned make sense there. I'll commit and merge?

**Comment by bknaepen** [comment]
Yes please :-)

**Comment by YelyzavetaV** [comment]
@Oedipsos Could you make a commit adding exactly what @bknaepen proposed in his comment above? It is easier this way, so that I won't clone your forked repo.

**Comment by bknaepen** [comment]
I realise I had settings.json in my gitignore. If we add .vscode then this is redundant I guess

**Comment by Oedipsos** [comment]
I did rebase my branch, bad idea, sorry for this... I added the files you mentioned, and also added some comments to add a kind of structure in it.

**Pull request merged**
